PortfolioGames.register({id:'precision-path',title:'Precision Path',description:'Trace wide, narrow, and curved paths with steady control.',mount(c){
 const s=HCI.session(c,'Drag from START to FINISH while staying inside the path. Three rounds: wide, narrow, curved. Hold the mouse button or keep your finger down. Releasing lets you resume at your last position. Mouse or touch required.');
 s.begin(()=>{let round=0,rows=[];
 function next(){const names=['Wide','Narrow','Curved'];s.bar.textContent=`Round ${round+1}/3 — ${names[round]}`;s.stage.replaceChildren();const canvas=document.createElement('canvas');canvas.width=480;canvas.height=280;canvas.setAttribute('aria-label',names[round]+' tracing path. Drag from left to right.');s.stage.append(canvas);const ctx=canvas.getContext('2d');if(!ctx){s.finish('Canvas is unavailable in this browser.');return;}
 const width=round===0?54:26,y=x=>round===2?140+65*Math.sin((x-25)/430*Math.PI*2):140;
 let dragging=false,pointer=null,started=0,last={x:25,y:y(25)},distance=0,crossings=0,outside=false,progress=25,ended=false;
 function draw(){ctx.clearRect(0,0,480,280);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#b7c7a4';ctx.lineWidth=width;ctx.beginPath();for(let x=25;x<=455;x+=2)x===25?ctx.moveTo(x,y(x)):ctx.lineTo(x,y(x));ctx.stroke();ctx.fillStyle='#193831';ctx.font='12px sans-serif';ctx.fillText('START',8,30);ctx.fillText('FINISH',425,30);ctx.beginPath();ctx.arc(last.x,last.y,6,0,Math.PI*2);ctx.fill();}
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*480/r.width,y:(e.clientY-r.top)*280/r.height};};
 s.on(canvas,'pointerdown',e=>{if(ended||s.start.hidden===false||e.button!==0)return;const p=point(e);if(Math.hypot(p.x-last.x,p.y-last.y)>25)return;e.preventDefault();dragging=true;pointer=e.pointerId;canvas.setPointerCapture(pointer);if(!started)started=performance.now();});
 s.on(canvas,'pointermove',e=>{if(!dragging||e.pointerId!==pointer||ended)return;const p=point(e),length=Math.hypot(p.x-last.x,p.y-last.y),steps=Math.max(1,Math.ceil(length));
 for(let i=1;i<=steps;i++){const x=last.x+(p.x-last.x)*i/steps,py=last.y+(p.y-last.y)*i/steps;const out=x<10||x>470||Math.abs(py-y(Math.max(25,Math.min(455,x))))>width/2;if(out&&!outside)crossings++;outside=out;progress=Math.max(progress,Math.min(455,x));}
 distance+=length;last=p;draw();if(progress>=450&&Math.hypot(p.x-455,p.y-y(455))<width/2){ended=true;dragging=false;rows.push(`${names[round]}: ${((performance.now()-started)/1000).toFixed(1)} s · ${crossings} boundary crossings · ${Math.round(distance)} path units`);round++;if(round===3){s.stage.textContent='Tracing complete';s.finish(rows.join('\n')+'\nCompare speed and errors separately. Path units use a fixed 480 × 280 coordinate space; devices differ.');}else{s.controls.replaceChildren();s.button('Next path',()=>{s.controls.replaceChildren();next();});}}});
 for(const type of ['pointerup','pointercancel','lostpointercapture'])s.on(canvas,type,()=>dragging=false);draw();}next();});return s.cleanup;
}});
